### ISSUE TITLE
Feature: Create public event handler to allow calling assemblies to receive instrumentation events from hypervm

### ISSUE THREAD

**Issue by gubanotorious** [CityOfZion/neo-hypervm#13]
When implementing neo-hypervm, calling assemblies will need to be able to attach an event handler(s) to receive instrumentation data created within the neo-hypervm.  I think we may want two separate events raised that we could attach separate event handlers to depending on the needs of the calling / referencing assembly.  

The two events I could see we need initially:
- Logging events with various classes of event (info, warning, error, etc)
- Performance instrumentation (timing metrics, etc)

**Comment by shargon** [comment]
It begins!

https://github.com/CityOfZion/neo-hypervm/tree/logs-feature
