### ISSUE TITLE
Feature: Create linked list for stack and its stack items

### ISSUE THREAD

**Issue by anthdm** [CityOfZion/neo-hypervm#14]
### Problem
A VM implementation needs to push and pop a lot of data. Using a stretchy buffer (which the std::list is) will need to grow a lot in a single program execution, an intensive operation.

### Solution
A double linked list will significantly improve performance. We could use a single linked list, but some DROP instructions will remove list items that are not on the top of the stack. I suggest using a double linked list implementation.

**Comment by shargon** [comment]
Acording to this http://en.cppreference.com/w/cpp/container/list `std::list` It is usually implemented as a doubly-linked list

**Comment by anthdm** [comment]
@shargon I see. Learning every day :). I assume that will do the trick. You can close this if you want.
