### ISSUE TITLE
Rename linux library

### ISSUE THREAD

**Issue by igormcoelho** [CityOfZion/neo-hypervm#46]
Shargon, I think linux static library must be renamed for easier use: "linux-libcrypto-x64.a" => "liblinux-libcrypto-x64.a". This "lib" prefix is very important in linux, it helps path resolution in compiling with "-L".
Congratulations, project is getting great! I'll take a deeper look in the next days/weeks/months :)

**Comment by shargon** [comment]
Fixed on https://github.com/CityOfZion/neo-hypervm/issues/46
